/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrcn_pck_alumno;

import hrcn_pck_alumno.Alumno;
import java.util.ArrayList;

/**
 *
 * @author cristian
 */
public class hrcn_form extends javax.swing.JFrame {

	/**
	 * Creates new form hrcn_form
	 */
	public hrcn_form() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                grupoGeneros = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                txtApellidoMaterno = new javax.swing.JTextField();
                txtNumControl = new javax.swing.JTextField();
                btnMostar = new javax.swing.JButton();
                btnAceptar = new javax.swing.JButton();
                btnCancelar = new javax.swing.JButton();
                lblCarrera = new javax.swing.JLabel();
                lblNombres = new javax.swing.JLabel();
                lblApellidoPaterno = new javax.swing.JLabel();
                txtNombre = new javax.swing.JTextField();
                txtApellidoPaterno = new javax.swing.JTextField();
                lblApellidoPaterno1 = new javax.swing.JLabel();
                optMasculino = new javax.swing.JRadioButton();
                optFemenino = new javax.swing.JRadioButton();
                lblNumeroControl = new javax.swing.JLabel();
                cboCarreras = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Alumno"));
                jPanel1.setToolTipText("");
                jPanel1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                jPanel1.setName("Datos del Alumno"); // NOI18N

                txtApellidoMaterno.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                txtApellidoMaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtApellidoMaternoActionPerformed(evt);
                        }
                });

                txtNumControl.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                txtNumControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                txtNumControl.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNumControlActionPerformed(evt);
                        }
                });

                btnMostar.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                btnMostar.setText("Mostrar");
                btnMostar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMostarActionPerformed(evt);
                        }
                });

                btnAceptar.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                btnAceptar.setText("Aceptar");
                btnAceptar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAceptarActionPerformed(evt);
                        }
                });

                btnCancelar.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                btnCancelar.setText("Cancelar");
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                lblCarrera.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblCarrera.setText("Carrera");

                lblNombres.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblNombres.setText("Nombres(s)");

                lblApellidoPaterno.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblApellidoPaterno.setText("Apellido Materno");

                txtNombre.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                txtNombre.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNombreActionPerformed(evt);
                        }
                });

                txtApellidoPaterno.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                txtApellidoPaterno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtApellidoPaternoActionPerformed(evt);
                        }
                });

                lblApellidoPaterno1.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblApellidoPaterno1.setText("Apellido Paterno");

                grupoGeneros.add(optMasculino);
                optMasculino.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                optMasculino.setSelected(true);
                optMasculino.setText("Masculino");
                optMasculino.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                optMasculinoActionPerformed(evt);
                        }
                });

                grupoGeneros.add(optFemenino);
                optFemenino.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                optFemenino.setText("Femenino");

                lblNumeroControl.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                lblNumeroControl.setText("Número de control");

                cboCarreras.setFont(new java.awt.Font("CaskaydiaCove NF", 0, 18)); // NOI18N
                cboCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Sistemas Computacionales", "Ingeniería Civil", "Ingeniería en Gestión Empresarial", "Ingeniería Electrónica", "Ingeniería Eléctrica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Química", "Licenciatura en Administración" }));
                cboCarreras.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cboCarrerasActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnMostar)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAceptar)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnCancelar))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(33, 33, 33)
                                                                                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(lblNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addGap(138, 138, 138))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                                .addComponent(lblApellidoPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(39, 39, 39)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(optMasculino)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(optFemenino)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblNumeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblApellidoPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblApellidoPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(optMasculino)
                                        .addComponent(optFemenino))
                                .addGap(35, 35, 35)
                                .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelar)
                                        .addComponent(btnAceptar)
                                        .addComponent(btnMostar))
                                .addGap(36, 36, 36))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void cboCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarrerasActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_cboCarrerasActionPerformed

        private void optMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMasculinoActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_optMasculinoActionPerformed

        private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtApellidoPaternoActionPerformed

        private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtNombreActionPerformed

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		// TODO add your handling code here:
		txtNombre.setText("");
		txtApellidoPaterno.setText("");
		txtApellidoMaterno.setText("");
		txtNumControl.setText("");
		cboCarreras.setSelectedItem("Ingeniería en Sistemas Computacionales");
		optMasculino.setSelected(true);
        }//GEN-LAST:event_btnCancelarActionPerformed

	public boolean checkFields() {
		String nombres = txtNombre.getText();
		if (!nombres.matches("^[a-zA-Z ]+$")) {
			System.out.println("El campo de nombres solo puede contener letras y espacios");
			return false;
		}

		String apellidoPaterno = txtApellidoPaterno.getText();
		if (!apellidoPaterno.matches("^[a-zA-Z]+$")) {
			System.out.println("El campo de apellido paterno solo puede contener letras");
			return false;
		}

		String apellidoMaterno = txtApellidoMaterno.getText();
		if (!apellidoMaterno.matches("^[a-zA-Z]+$")) {
			System.out.println("El campo de apellido materno solo puede contener letras");
			return false;
		}

		String numeroControl = txtNumControl.getText();
		if (numeroControl.length() != 8) {
			System.out.println("Ingresa un numero de control de 8 digitos");
			return false;
		}

		if (nombres.equals("") || apellidoPaterno.equals("") || apellidoMaterno.equals("") || numeroControl.equals("")) {
			System.out.println("Ingresa todos los valores solicitados");
			return false;
		}

		return true;
	}

        private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
		// TODO add your handling code here:
		if (!checkFields()) {
			return;
		}

		String nombres = txtNombre.getText();
		String apellidoPaterno = txtApellidoPaterno.getText();
		String apellidoMaterno = txtApellidoMaterno.getText();
		String numeroControl = txtNumControl.getText();
		char genero = optMasculino.isSelected() ? 'M' : 'F';
		String carrera = (String) cboCarreras.getSelectedItem();
		Alumno alumno = new Alumno(nombres, apellidoPaterno, apellidoMaterno, numeroControl, genero, carrera);
		alumnos.add(alumno);
		txtNombre.setText("");
		txtApellidoPaterno.setText("");
		txtApellidoMaterno.setText("");
		txtNumControl.setText("");
		System.out.println("Alumno almacenado correctamente");
        }//GEN-LAST:event_btnAceptarActionPerformed

        private void btnMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarActionPerformed
		// TODO add your handling code here:
		if (alumnos.isEmpty()) {
			System.out.println("No se encontraron alumnos registrados");
		} else {
			for (Alumno alumno : alumnos) {
				System.out.println(alumno);
			}
		}
        }//GEN-LAST:event_btnMostarActionPerformed

        private void txtNumControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumControlActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtNumControlActionPerformed

        private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_txtApellidoMaternoActionPerformed

	private ArrayList<Alumno> alumnos = new ArrayList<>();

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(hrcn_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(hrcn_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(hrcn_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(hrcn_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new hrcn_form().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAceptar;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JButton btnMostar;
        private javax.swing.JComboBox<String> cboCarreras;
        private javax.swing.ButtonGroup grupoGeneros;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblApellidoPaterno;
        private javax.swing.JLabel lblApellidoPaterno1;
        private javax.swing.JLabel lblCarrera;
        private javax.swing.JLabel lblNombres;
        private javax.swing.JLabel lblNumeroControl;
        private javax.swing.JRadioButton optFemenino;
        private javax.swing.JRadioButton optMasculino;
        private javax.swing.JTextField txtApellidoMaterno;
        private javax.swing.JTextField txtApellidoPaterno;
        private javax.swing.JTextField txtNombre;
        private javax.swing.JTextField txtNumControl;
        // End of variables declaration//GEN-END:variables
}
